#!/bin/bash
set -e 

apt update

# General
apt install -y software-properties-common xdotool gnome-characters flameshot htop xclip npm expect cheese rig chrome-gnome-shell pwgen nautilus-dropbox nemo rar unrar vlc composer  openssh-server kolourpaint filezilla gedit gimp git meld gnupg python3 apt-transport-https ca-certificates curl software-properties-common jq sublime-text copyq

# Docker / Docker Compose
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update -y
sudo apt install -y docker-ce docker-ce-cli containerd.io
docker --version
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker
sudo chown root:docker /var/run/docker.sock
sudo chown -R root:docker /var/run/docker
docker run hello-world

# Install Node.js via 'n'
sudo npm install -g n
sudo n lts
sudo ln -sf /usr/local/bin/node /usr/bin/node
sudo ln -sf /usr/local/bin/npm /usr/bin/npm
node -v
npm -v


read -p "All Done. Hit anything on <enter> key to exit. " X
exit 0
